name: PlayersManipulationAPI
version: '${project.version}'
main: pe.bazan.luis.plugins.playersmanipulationapi.PlayersManipulationAPI
api-version: '1.20'
authors: [Luis Bazan]
depend:
  - KitsAPI
description: An API to easy players management for server events or other occasions
commands:
  playersmanipulationapi:
    permission: manipulationapi.commands
    description: Main command of the plugin
    usage: /playersmanipulationapi help
